name 'database-loader'
maintainer 'Jannik Zinkl, Tilman Marquart'
maintainer_email 'jannik.zinkl@telekom.de, tilman.marquart@telekom.de'
license 'all_rights'
description 'Used to insert configuration/csv-files into a MYSQL-database'
long_description 'This cookbook overcomes the problems of bloated mysql-cookbooks with a lot of dependencies'
version '0.3.1'
